### ISSUE TITLE
I can't run Youtube15

### ISSUE THREAD

**Issue by titan08kn** [haidarn2/Youtube15#1]
Hello, if i run Youtube15 on keyboard display is show system.net.httplistenerexception access is denied.

- If I tried run as admin a have this error 
![b](https://cloud.githubusercontent.com/assets/25273872/22179154/7a353bec-e04b-11e6-9991-9f8cd8b10b2b.png)

I tried look on google, but I can't foud any solution :-( Can you help? please.
YouTube15_v1.2, Win 7 64bit, Chrome extension
 

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Double.Parse(String s)
   at YouTube15.YouTube15.UpdateLcd()
   at YouTube15.YouTube15.OnLcdTimer(Object source, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
YouTube15
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Sta%C5%BEen%C3%A9%20soubory/YouTube15_v1.2/YouTube15.exe
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.IdentityModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 4.5.0.0
    Win32 Version: 5.0.6.16206
    CodeBase: file:///D:/Sta%C5%BEen%C3%A9%20soubory/YouTube15_v1.2/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by haidarn2** [comment]
Hi, thanks for reporting this issue.
You do **not** need to run Youtube15 as administrator, it should work just fine running it normally.

**System.Net.Httplistenerexception: access is denied** usually means the port that YouTube15 is trying to host on is already in use. Currently YouTube15 uses port **60024** but you may already have some other application that is using that port.

Please test this custom build that uses a different port (**60025**) so we can determine if that is the cause: 
[YouTube15_v1.2_testbuild_port60025.zip](https://github.com/haidarn2/Youtube15/files/722054/YouTube15_v1.2_testbuild_port60025.zip)


This build will not work with the current chrome/firefox extension because they use port **60024** but you should at-least be able to get to the idle screen that shows the clock:

![clock image](http://i.imgur.com/WkbHWJE.png)

**Comment by titan08kn** [comment]
Hi, I tried YouTube15_v1.2_testbuild_port60025, but again the same issue :-( I tried run Windows clean startup ( I am trying everything ) same :-(

**Comment by haidarn2** [comment]
Hmm.. That's very odd, here's another custom build this time with debug logging enabled.

I changed the code so that if it crashes now it will just write to the log and close instead of displaying the error.

When you run YouTube15, it will create a log file in the **Log** Folder. Please create 2 log files, one **without admin** privileges and one with **admin**. 

_Don't forget to rename the log file between runs so it doesn't use the same log!_

[YouTube15_v1.2_testbuild_logging.zip](https://github.com/haidarn2/Youtube15/files/725536/YouTube15_v1.2_testbuild_logging.zip)

**Comment by titan08kn** [comment]
Ok. I can't upload zip file. I don't know why. So I upload here:  https://drive.google.com/file/d/0By_AT_9CeZd9NUNueHFkZnh5RTQ/view?usp=sharing

**Comment by haidarn2** [comment]
Thank you for the logs!

It appears that I was wrong, you **do** indeed have to run it in admin mode. It seems to be hosting on port 60024 just fine in admin mode.

I also figured out why it's crashing. The admin log shows that YouTube15 is crashing when you open a video and it begins to receive data from the browser extension (eg current position, video title, etc). It crashes because decimal localization on your PC is different (eg **0,23** seconds vs **0.23** seconds) so it does not know how to deal with it. 

I will work on a fix tonight and update Youtube15 to version 1.3. I'll post here when that's done. Thanks again for the logs!

**Comment by haidarn2** [comment]
Here it is, please test it out and let me know if it works before I release it officially.

[YouTube15_v1.3_prerelease.zip](https://github.com/haidarn2/Youtube15/files/728387/YouTube15_v1.3_prerelease.zip)
_(Don't forget you need to run it as **admin**!)_

**Comment by titan08kn** [comment]
Hi, v1.3 works perfectly fine! This issue is fixed, great! Good job :-) I found one small issue and maybe one idea.
YouTube15 won’t start automatically (with admin rights). After check autostart, applications will not start. I don’t know if this happened becasue YouTube15 starts with admin rights or…

When playing video everything is fine, but if I open YouTube link as new tab (Up next video open as new tab), YouTube15 stay at first video even if I close tab with the first video. If I click normaly it’s fine. (stay at the same tab) It would be great If YouTube15 works with every tab no matter how was tab launched. Just an idea (I hope I described comprehensibly :-) )

**Comment by haidarn2** [comment]
Thank you for testing it!

I am still working out the admin issue (On my PC it doesn't need admin, so It's hard for me to test) and the autostart issue is a known one. I am working on fixing both of them by the next release.

If I'm understanding you correctly you're saying that having videos in multiple tabs is not working properly? This shouldn't be the case, I recorded this video showing that multiple tabs do work fine: https://u.nya.is/sosrxk.mp4

_(The G15 emulator is on the upper right side, **sorry** if it's hard to see!)_

Also if you don't mind me asking are you using Firefox or Chrome?

**Comment by titan08kn** [comment]
If it would help, I’ll test for you. No problem. :-) I using Chrome

Exactly what I wrote. But I'm sorry. I tried to turn off my extensions and after that YouTube15 work fine with any tab. Some extension that I have block this function. Issue on my side :-)
